name: Update badges

on:
  push:
    branches: ["*"]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Create coverage badge
      run: |
        pip install requests pytest pytest-cov
        python badgecreator.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'chore: update coverage badge'
        add: '*.svg'
      
